export const hotel_rooms = [
    {
        id: 1,
        link: "#",
        image: "/img/hotel_rooms/hotel_rooms_001.jpg", 
        type: "Lorem ipsum dolor sit amet.", 
        size_sqf: "123", 
        size_sqm: "123", 
        view: "sea view", 
        beds: "1 king bed",
    },
        {
        id: 2,
        link: "#",
        image: "/img/hotel_rooms/hotel_rooms_002.jpg", 
        type: "Lorem ipsum dolor sit amet.", 
        size_sqf: "123", 
        size_sqm: "123", 
        view: "sea view", 
        beds: "1 king bed",
    },
        {
        id: 3,
        link: "#",
        image: "/img/hotel_rooms/hotel_rooms_003.jpg", 
        type: "Lorem ipsum dolor sit amet.", 
        size_sqf: "123", 
        size_sqm: "123", 
        view: "sea view", 
        beds: "1 king bed",
    },
        {
        id: 4,
        link: "#",
        image: "/img/hotel_rooms/hotel_rooms_001.jpg", 
        type: "Lorem ipsum dolor sit amet.", 
        size_sqf: "123", 
        size_sqm: "123", 
        view: "sea view", 
        beds: "1 king bed",
    },
]