export const hotel_rooms = [
    {
        id: 1,
        link: "#",
        image: "/img/hotel_rooms/hotel_rooms_001.webp", 
        type: "standard room", 
        size_sqf: "2160", 
        size_sqm: "200", 
        view: "cyberpunk city view", 
        beds: "1 queen bed",
        list1: "In-room safe deposit box",
        list2: "Laundry and dry-cleaning services",
        list3: "Double-glazed floor-to-ceiling windows",
        list4: "Complimentary Wi-Fi Internet access",
        list5: "55' 4K UHD Smart TV with local, international channels and screen mirroring options",
        list6: "BALMAIN bathroom amenity collection",
        list7: "Wall-mounted rain shower in all rooms and additional bathtub in king rooms only",
        list8: "Stylish vanity table with illuminated shaving / make-up mirror",
        list9: "Hairdryer and digital bathroom scale",
        list10: "Individual temperature control",
    },
        {
        id: 2,
        link: "#",
        image: "/img/hotel_rooms/hotel_rooms_002.webp", 
        type: "deluxe room", 
        size_sqf: "2700", 
        size_sqm: "250", 
        view: "cyberpunk city view", 
        beds: "1 king bed",
        list1: "In-room safe deposit box",
        list2: "Laundry and dry-cleaning services",
        list3: "Double-glazed floor-to-ceiling windows",
        list4: "Complimentary Wi-Fi Internet access",
        list5: "55' 4K UHD Smart TV with local, international channels and screen mirroring options",
        list6: "BALMAIN bathroom amenity collection",
        list7: "Wall-mounted rain shower in all rooms and additional bathtub in king rooms only",
        list8: "Stylish vanity table with illuminated shaving / make-up mirror",
        list9: "Hairdryer and digital bathroom scale",
        list10: "Individual temperature control",
    },
        {
        id: 3,
        link: "#",
        image: "/img/hotel_rooms/hotel_rooms_003.webp", 
        type: "premier room", 
        size_sqf: "3240", 
        size_sqm: "300", 
        view: "cyberpunk city view", 
        beds: "1 king bed & 1 queen bed",
        list1: "In-room safe deposit box",
        list2: "Laundry and dry-cleaning services",
        list3: "Double-glazed floor-to-ceiling windows",
        list4: "Complimentary Wi-Fi Internet access",
        list5: "55' 4K UHD Smart TV with local, international channels and screen mirroring options",
        list6: "BALMAIN bathroom amenity collection",
        list7: "Wall-mounted rain shower in all rooms and additional bathtub in king rooms only",
        list8: "Stylish vanity table with illuminated shaving / make-up mirror",
        list9: "Hairdryer and digital bathroom scale",
        list10: "Individual temperature control",
    },
        {
        id: 4,
        link: "#",
        image: "/img/hotel_rooms/hotel_rooms_001.webp", 
        type: "grand room", 
        size_sqf: "4320", 
        size_sqm: "400", 
        view: "cyberpunk city view", 
        beds: "2 king beds",
        list1: "In-room safe deposit box",
        list2: "Laundry and dry-cleaning services",
        list3: "Double-glazed floor-to-ceiling windows",
        list4: "Complimentary Wi-Fi Internet access",
        list5: "55' 4K UHD Smart TV with local, international channels and screen mirroring options",
        list6: "BALMAIN bathroom amenity collection",
        list7: "Wall-mounted rain shower in all rooms and additional bathtub in king rooms only",
        list8: "Stylish vanity table with illuminated shaving / make-up mirror",
        list9: "Hairdryer and digital bathroom scale",
        list10: "Individual temperature control",
    },
]

export const hotel_dining = [
    {
        id: "1",
        name: "Restaurant A",
        image: "/img/hotel_dining/hotel_dining_restaurant01.webp",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium ea debitis dolorem ut doloremque, nobis eius! Ullam minima amet quam autem praesentium nobis? Neque, iste? Aliquam necessitatibus fugit porro ducimus.",
        list1: "aaaaaa",
        list2: "bbbbbb",
        list3: "cccccc",
        list4: "dddddd",
    },
    {
        id: "2",
        name: "Restaurant B",
        image: "/img/hotel_dining/hotel_dining_restaurant02.webp",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium ea debitis dolorem ut doloremque, nobis eius! Ullam minima amet quam autem praesentium nobis? Neque, iste? Aliquam necessitatibus fugit porro ducimus.",
        list1: "aaaaaa",
        list2: "bbbbbb",
        list3: "cccccc",
        list4: "dddddd",
    },
    {
        id: "3",
        name: "Restaurant C",
        image: "/img/hotel_dining/hotel_dining_restaurant03.webp",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium ea debitis dolorem ut doloremque, nobis eius! Ullam minima amet quam autem praesentium nobis? Neque, iste? Aliquam necessitatibus fugit porro ducimus.",
        list1: "aaaaaa",
        list2: "bbbbbb",
        list3: "cccccc",
        list4: "dddddd",
    },
    {
        id: "4",
        name: "Bar",
        image: "/img/hotel_dining/hotel_dining_bar01.webp",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium ea debitis dolorem ut doloremque, nobis eius! Ullam minima amet quam autem praesentium nobis? Neque, iste? Aliquam necessitatibus fugit porro ducimus.",
        list1: "aaaaaa",
        list2: "bbbbbb",
        list3: "cccccc",
        list4: "dddddd",
    },
]

export const hotel_facilities = [
    {
        id: "1",
        name: "Swimming Pool",
        image: "/img/hotel_facilities/hotel_facilities_pool.webp",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium ea debitis dolorem ut doloremque, nobis eius! Ullam minima amet quam autem praesentium nobis? Neque, iste? Aliquam necessitatibus fugit porro ducimus.",
        list1: "aaaaaa",
        list2: "bbbbbb",
        list3: "cccccc",
        list4: "dddddd",
    },
    {
        id: "2",
        name: "GYM",
        image: "/img/hotel_facilities/hotel_facilities_gym.webp",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium ea debitis dolorem ut doloremque, nobis eius! Ullam minima amet quam autem praesentium nobis? Neque, iste? Aliquam necessitatibus fugit porro ducimus.",
        list1: "aaaaaa",
        list2: "bbbbbb",
        list3: "cccccc",
        list4: "dddddd",
    },
    {
        id: "3",
        name: "SPA",
        image: "/img/hotel_facilities/hotel_facilities_spa.webp",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium ea debitis dolorem ut doloremque, nobis eius! Ullam minima amet quam autem praesentium nobis? Neque, iste? Aliquam necessitatibus fugit porro ducimus.",
        list1: "aaaaaa",
        list2: "bbbbbb",
        list3: "cccccc",
        list4: "dddddd",
    },
    {
        id: "4",
        name: "Kid's Zone",
        image: "/img/hotel_facilities/hotel_facilities_kidzone.webp",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium ea debitis dolorem ut doloremque, nobis eius! Ullam minima amet quam autem praesentium nobis? Neque, iste? Aliquam necessitatibus fugit porro ducimus.",
        list1: "aaaaaa",
        list2: "bbbbbb",
        list3: "cccccc",
        list4: "dddddd",
    },
]

export const contact_us_contact_info_table_data = [
    {
        id: "1",
        subject: "General",
        email: "general_cyberpunkhk@gmail.com",
    },
        {
        id: "2",
        subject: "Hotel",
        email: "hotel_cyberpunkhk@gmail.com",
    },
        {
        id: "3",
        subject: "Restaurant",
        email: "restaurant_cyberpunkhk@gmail.com",
    },
        {
        id: "4",
        subject: "Online shop",
        email: "onlineshop_cyberpunkhk@gmail.com",
    },
]   

export const contact_us_bus_table_data_hki = [
    {
        id: "1",
        company: "AAA",
        number: "101",
        route: "QQ to WW",
    },
        {
        id: "2",
        company: "BBB",
        number: "670",
        route: "RR to TT",
    },
]

export const contact_us_bus_table_data_kt = [
    {
        id: "1",
        company: "AAA",
        number: "150",
        route: "gg to hh",
    },
        {
        id: "2",
        company: "BBB",
        number: "555",
        route: "UU to BB",
    },
]

export const contact_us_minibus_table_data_nt = [
    {
        id: "1",
        company: "AAA",
        number: "400",
        route: "gg to hh",
    },
        {
        id: "2",
        company: "BBB",
        number: "600",
        route: "UU to BB",
    },
]

export const contact_us_minibus_table_data_hki = [
    {
        id: "1",
        company: "AAA",
        number: "101",
        route: "QQ to WW",
    },
        {
        id: "2",
        company: "BBB",
        number: "670",
        route: "RR to TT",
    },
]

export const contact_us_minibus_table_data_kt = [
    {
        id: "1",
        company: "AAA",
        number: "150",
        route: "gg to hh",
    },
        {
        id: "2",
        company: "BBB",
        number: "555",
        route: "UU to BB",
    },
]

export const contact_us_bus_table_data_nt = [
    {
        id: "1",
        company: "AAA",
        number: "400",
        route: "gg to hh",
    },
        {
        id: "2",
        company: "BBB",
        number: "600",
        route: "UU to BB",
    },
]

export const contact_us_carpark_table_data = [
    {
        id: "1",
        days: "Mon - Fri",
        fee: "$50/hr",
    },
    {
        id: "2",
        days: "Sat - Sun",
        fee: "$70/hr",
    },
]

export const job_openings = [
    {
        id: '1',
        post_date: '15-08-2025',
        job_title: 'Electrical & Mechanical Technician',
        department: 'Rides Maintenance and Ropeway',
        job_type: 'Full-time / Long-term',
        link: '#',
        responsibilities1: 'Prepare invoices / vouchers on a daily basis and support the account payables and receivables functions of the Finance Department',
        responsibilities2: 'Perform annual spot check of Fixed Assets',
        responsibilities3: 'Perform monthly surprise stock check and annual stock take',
        responsibilities4: 'Perform ad hoc assignments as and when required',
        requirements1: "Bachelor's Degree in Accounting or at least one year of relevant working experience",
        requirements2: 'Able to work under pressure, and commit to reporting deadlines',
        requirements3: 'Detailed-oriented and with strong sense of responsibilities',
        requirements4: 'Well-organized, and a team player with the ability to work with parties across different departments',
        benefits1: '13-month payment / Gratuity',
        benefits2: 'Medical Insurance (Hospitalization & Outpatient)',
        benefits3: '14 days Paid Leave',
        benefits4: '17 days Public Holiday',
    },
        {
        id: '2',
        post_date: '15-08-2025',
        job_title: 'Senior Manager, Risk & Sustainability',
        department: 'Risk & Sustainability',
        job_type: 'Full-time / Long-term',
        link: '#',
        responsibilities1: 'Prepare invoices / vouchers on a daily basis and support the account payables and receivables functions of the Finance Department',
        responsibilities2: 'Perform annual spot check of Fixed Assets',
        responsibilities3: 'Perform monthly surprise stock check and annual stock take',
        responsibilities4: 'Perform ad hoc assignments as and when required',
        requirements1: "Bachelor's Degree in Accounting or at least one year of relevant working experience",
        requirements2: 'Able to work under pressure, and commit to reporting deadlines',
        requirements3: 'Detailed-oriented and with strong sense of responsibilities',
        requirements4: 'Well-organized, and a team player with the ability to work with parties across different departments',
        benefits1: '13-month payment / Gratuity',
        benefits2: 'Medical Insurance (Hospitalization & Outpatient)',
        benefits3: '14 days Paid Leave',
        benefits4: '17 days Public Holiday',
    },
        {
        id: '3',
        post_date: '15-08-2025',
        job_title: 'Assistant Buying Manager / Senior Buyer (HK$6000 New Joiner Incentive)',
        department: 'ARetail Operations',
        job_type: 'Full-time / Long-term',
        link: '#',
        responsibilities1: 'Prepare invoices / vouchers on a daily basis and support the account payables and receivables functions of the Finance Department',
        responsibilities2: 'Perform annual spot check of Fixed Assets',
        responsibilities3: 'Perform monthly surprise stock check and annual stock take',
        responsibilities4: 'Perform ad hoc assignments as and when required',
        requirements1: "Bachelor's Degree in Accounting or at least one year of relevant working experience",
        requirements2: 'Able to work under pressure, and commit to reporting deadlines',
        requirements3: 'Detailed-oriented and with strong sense of responsibilities',
        requirements4: 'Well-organized, and a team player with the ability to work with parties across different departments',
        benefits1: '13-month payment / Gratuity',
        benefits2: 'Medical Insurance (Hospitalization & Outpatient)',
        benefits3: '14 days Paid Leave',
        benefits4: '17 days Public Holiday',
    },
        {
        id: '4',
        post_date: '15-08-2025',
        job_title: 'Technical Manager, Ropeway',
        department: 'Rides Maintenance and Ropeway',
        job_type: 'Full-time / Long-term',
        link: '#',
        responsibilities1: 'Prepare invoices / vouchers on a daily basis and support the account payables and receivables functions of the Finance Department',
        responsibilities2: 'Perform annual spot check of Fixed Assets',
        responsibilities3: 'Perform monthly surprise stock check and annual stock take',
        responsibilities4: 'Perform ad hoc assignments as and when required',
        requirements1: "Bachelor's Degree in Accounting or at least one year of relevant working experience",
        requirements2: 'Able to work under pressure, and commit to reporting deadlines',
        requirements3: 'Detailed-oriented and with strong sense of responsibilities',
        requirements4: 'Well-organized, and a team player with the ability to work with parties across different departments',
        benefits1: '13-month payment / Gratuity',
        benefits2: 'Medical Insurance (Hospitalization & Outpatient)',
        benefits3: '14 days Paid Leave',
        benefits4: '17 days Public Holiday',
    },
        {
        id: '5',
        post_date: '15-08-2025',
        job_title: 'First Aid Supervisor',
        department: 'Space World First Aid',
        job_type: 'Full-time / Long-term',
        link: '#',
        responsibilities1: 'Prepare invoices / vouchers on a daily basis and support the account payables and receivables functions of the Finance Department',
        responsibilities2: 'Perform annual spot check of Fixed Assets',
        responsibilities3: 'Perform monthly surprise stock check and annual stock take',
        responsibilities4: 'Perform ad hoc assignments as and when required',
        requirements1: "Bachelor's Degree in Accounting or at least one year of relevant working experience",
        requirements2: 'Able to work under pressure, and commit to reporting deadlines',
        requirements3: 'Detailed-oriented and with strong sense of responsibilities',
        requirements4: 'Well-organized, and a team player with the ability to work with parties across different departments',
        benefits1: '13-month payment / Gratuity',
        benefits2: 'Medical Insurance (Hospitalization & Outpatient)',
        benefits3: '14 days Paid Leave',
        benefits4: '17 days Public Holiday',
    },
        {
        id: '6',
        post_date: '15-08-2025',
        job_title: 'Security Operations - Security Guard/Security Guard In-charge/Security Supervisor',
        department: 'Security Operations',
        job_type: 'Full-time / Long-term',
        link: '#',
        responsibilities1: 'Prepare invoices / vouchers on a daily basis and support the account payables and receivables functions of the Finance Department',
        responsibilities2: 'Perform annual spot check of Fixed Assets',
        responsibilities3: 'Perform monthly surprise stock check and annual stock take',
        responsibilities4: 'Perform ad hoc assignments as and when required',
        requirements1: "Bachelor's Degree in Accounting or at least one year of relevant working experience",
        requirements2: 'Able to work under pressure, and commit to reporting deadlines',
        requirements3: 'Detailed-oriented and with strong sense of responsibilities',
        requirements4: 'Well-organized, and a team player with the ability to work with parties across different departments',
        benefits1: '13-month payment / Gratuity',
        benefits2: 'Medical Insurance (Hospitalization & Outpatient)',
        benefits3: '14 days Paid Leave',
        benefits4: '17 days Public Holiday',
    },
        {
        id: '7',
        post_date: '15-08-2025',
        job_title: 'Short Term / Seasonal Part Time Traffic Attendant ',
        department: 'Transportation Services',
        job_type: 'Part-time / Short-term',
        link: '#',
        responsibilities1: 'Prepare invoices / vouchers on a daily basis and support the account payables and receivables functions of the Finance Department',
        responsibilities2: 'Perform annual spot check of Fixed Assets',
        responsibilities3: 'Perform monthly surprise stock check and annual stock take',
        responsibilities4: 'Perform ad hoc assignments as and when required',
        requirements1: "Bachelor's Degree in Accounting or at least one year of relevant working experience",
        requirements2: 'Able to work under pressure, and commit to reporting deadlines',
        requirements3: 'Detailed-oriented and with strong sense of responsibilities',
        requirements4: 'Well-organized, and a team player with the ability to work with parties across different departments',
        benefits1: '13-month payment / Gratuity',
        benefits2: 'Medical Insurance (Hospitalization & Outpatient)',
        benefits3: '14 days Paid Leave',
        benefits4: '17 days Public Holiday',
    },
        {
        id: '8',
        post_date: '15-08-2025',
        job_title: 'Veterinary Intern',
        department: 'Veterinary',
        job_type: 'Part-time / Short-term',
        link: '#',
        responsibilities1: 'Prepare invoices / vouchers on a daily basis and support the account payables and receivables functions of the Finance Department',
        responsibilities2: 'Perform annual spot check of Fixed Assets',
        responsibilities3: 'Perform monthly surprise stock check and annual stock take',
        responsibilities4: 'Perform ad hoc assignments as and when required',
        requirements1: "Bachelor's Degree in Accounting or at least one year of relevant working experience",
        requirements2: 'Able to work under pressure, and commit to reporting deadlines',
        requirements3: 'Detailed-oriented and with strong sense of responsibilities',
        requirements4: 'Well-organized, and a team player with the ability to work with parties across different departments',
        benefits1: '13-month payment / Gratuity',
        benefits2: 'Medical Insurance (Hospitalization & Outpatient)',
        benefits3: '14 days Paid Leave',
        benefits4: '17 days Public Holiday',
    },
        {
        id: '9',
        post_date: '15-08-2025',
        job_title: 'Contract Designer',
        department: 'Events & Entertainment',
        job_type: 'Full-time / Long-term',
        link: '#',
        responsibilities1: 'Prepare invoices / vouchers on a daily basis and support the account payables and receivables functions of the Finance Department',
        responsibilities2: 'Perform annual spot check of Fixed Assets',
        responsibilities3: 'Perform monthly surprise stock check and annual stock take',
        responsibilities4: 'Perform ad hoc assignments as and when required',
        requirements1: "Bachelor's Degree in Accounting or at least one year of relevant working experience",
        requirements2: 'Able to work under pressure, and commit to reporting deadlines',
        requirements3: 'Detailed-oriented and with strong sense of responsibilities',
        requirements4: 'Well-organized, and a team player with the ability to work with parties across different departments',
        benefits1: '13-month payment / Gratuity',
        benefits2: 'Medical Insurance (Hospitalization & Outpatient)',
        benefits3: '14 days Paid Leave',
        benefits4: '17 days Public Holiday',
    },
        {
        id: '10',
        post_date: '15-08-2025',
        job_title: 'Creative Brand Manager (IP Management)',
        department: 'Intellectual Properties Business',
        job_type: 'Full-time / Long-term',
        link: '#',
        responsibilities1: 'Prepare invoices / vouchers on a daily basis and support the account payables and receivables functions of the Finance Department',
        responsibilities2: 'Perform annual spot check of Fixed Assets',
        responsibilities3: 'Perform monthly surprise stock check and annual stock take',
        responsibilities4: 'Perform ad hoc assignments as and when required',
        requirements1: "Bachelor's Degree in Accounting or at least one year of relevant working experience",
        requirements2: 'Able to work under pressure, and commit to reporting deadlines',
        requirements3: 'Detailed-oriented and with strong sense of responsibilities',
        requirements4: 'Well-organized, and a team player with the ability to work with parties across different departments',
        benefits1: '13-month payment / Gratuity',
        benefits2: 'Medical Insurance (Hospitalization & Outpatient)',
        benefits3: '14 days Paid Leave',
        benefits4: '17 days Public Holiday',
    },
        {
        id: '11',
        post_date: '15-08-2025',
        job_title: 'Ticketing Assistant / Attendant',
        department: 'Main Entrance Operations',
        job_type: 'Full-time / Long-term',
        link: '#',
        responsibilities1: 'Prepare invoices / vouchers on a daily basis and support the account payables and receivables functions of the Finance Department',
        responsibilities2: 'Perform annual spot check of Fixed Assets',
        responsibilities3: 'Perform monthly surprise stock check and annual stock take',
        responsibilities4: 'Perform ad hoc assignments as and when required',
        requirements1: "Bachelor's Degree in Accounting or at least one year of relevant working experience",
        requirements2: 'Able to work under pressure, and commit to reporting deadlines',
        requirements3: 'Detailed-oriented and with strong sense of responsibilities',
        requirements4: 'Well-organized, and a team player with the ability to work with parties across different departments',
        benefits1: '13-month payment / Gratuity',
        benefits2: 'Medical Insurance (Hospitalization & Outpatient)',
        benefits3: '14 days Paid Leave',
        benefits4: '17 days Public Holiday',
    },
        {
        id: '12',
        post_date: '15-08-2025',
        job_title: 'Technician (Admin/ AV & Lighting)',
        department: 'Events & Entertainment',
        job_type: 'Full-time / Long-term',
        link: '#',
        responsibilities1: 'Prepare invoices / vouchers on a daily basis and support the account payables and receivables functions of the Finance Department',
        responsibilities2: 'Perform annual spot check of Fixed Assets',
        responsibilities3: 'Perform monthly surprise stock check and annual stock take',
        responsibilities4: 'Perform ad hoc assignments as and when required',
        requirements1: "Bachelor's Degree in Accounting or at least one year of relevant working experience",
        requirements2: 'Able to work under pressure, and commit to reporting deadlines',
        requirements3: 'Detailed-oriented and with strong sense of responsibilities',
        requirements4: 'Well-organized, and a team player with the ability to work with parties across different departments',
        benefits1: '13-month payment / Gratuity',
        benefits2: 'Medical Insurance (Hospitalization & Outpatient)',
        benefits3: '14 days Paid Leave',
        benefits4: '17 days Public Holiday',
    },
        {
        id: '13',
        post_date: '15-08-2025',
        job_title: 'Contract Communications Officer (HK$6000 New Joiner Incentive)',
        department: 'General Services',
        job_type: 'Part-time / Short-term',
        link: '#',
        responsibilities1: 'Prepare invoices / vouchers on a daily basis and support the account payables and receivables functions of the Finance Department',
        responsibilities2: 'Perform annual spot check of Fixed Assets',
        responsibilities3: 'Perform monthly surprise stock check and annual stock take',
        responsibilities4: 'Perform ad hoc assignments as and when required',
        requirements1: "Bachelor's Degree in Accounting or at least one year of relevant working experience",
        requirements2: 'Able to work under pressure, and commit to reporting deadlines',
        requirements3: 'Detailed-oriented and with strong sense of responsibilities',
        requirements4: 'Well-organized, and a team player with the ability to work with parties across different departments',
        benefits1: '13-month payment / Gratuity',
        benefits2: 'Medical Insurance (Hospitalization & Outpatient)',
        benefits3: '14 days Paid Leave',
        benefits4: '17 days Public Holiday',
    },
        {
        id: '14',
        post_date: '15-08-2025',
        job_title: 'Food & Beverage - Part Time Job Openings',
        department: 'Food & Beverage',
        job_type: 'Part-time / Short-term',
        link: '#',
        responsibilities1: 'Prepare invoices / vouchers on a daily basis and support the account payables and receivables functions of the Finance Department',
        responsibilities2: 'Perform annual spot check of Fixed Assets',
        responsibilities3: 'Perform monthly surprise stock check and annual stock take',
        responsibilities4: 'Perform ad hoc assignments as and when required',
        requirements1: "Bachelor's Degree in Accounting or at least one year of relevant working experience",
        requirements2: 'Able to work under pressure, and commit to reporting deadlines',
        requirements3: 'Detailed-oriented and with strong sense of responsibilities',
        requirements4: 'Well-organized, and a team player with the ability to work with parties across different departments',
        benefits1: '13-month payment / Gratuity',
        benefits2: 'Medical Insurance (Hospitalization & Outpatient)',
        benefits3: '14 days Paid Leave',
        benefits4: '17 days Public Holiday',
    },
        {
        id: '15',
        post_date: '15-08-2025',
        job_title: 'Programme Trainer/ Facilitator',
        department: 'Events & Entertainment',
        job_type: 'Full-time / Long-termSK',
        link: '#',
        responsibilities1: 'Prepare invoices / vouchers on a daily basis and support the account payables and receivables functions of the Finance Department',
        responsibilities2: 'Perform annual spot check of Fixed Assets',
        responsibilities3: 'Perform monthly surprise stock check and annual stock take',
        responsibilities4: 'Perform ad hoc assignments as and when required',
        requirements1: "Bachelor's Degree in Accounting or at least one year of relevant working experience",
        requirements2: 'Able to work under pressure, and commit to reporting deadlines',
        requirements3: 'Detailed-oriented and with strong sense of responsibilities',
        requirements4: 'Well-organized, and a team player with the ability to work with parties across different departments',
        benefits1: '13-month payment / Gratuity',
        benefits2: 'Medical Insurance (Hospitalization & Outpatient)',
        benefits3: '14 days Paid Leave',
        benefits4: '17 days Public Holiday',
    },
        {
        id: '16',
        post_date: '15-08-2025',
        job_title: 'Parkwide Decoration Assistant',
        department: 'Discovery & Education',
        job_type: 'Full-time / Long-term',
        link: '#',
        responsibilities1: 'Prepare invoices / vouchers on a daily basis and support the account payables and receivables functions of the Finance Department',
        responsibilities2: 'Perform annual spot check of Fixed Assets',
        responsibilities3: 'Perform monthly surprise stock check and annual stock take',
        responsibilities4: 'Perform ad hoc assignments as and when required',
        requirements1: "Bachelor's Degree in Accounting or at least one year of relevant working experience",
        requirements2: 'Able to work under pressure, and commit to reporting deadlines',
        requirements3: 'Detailed-oriented and with strong sense of responsibilities',
        requirements4: 'Well-organized, and a team player with the ability to work with parties across different departments',
        benefits1: '13-month payment / Gratuity',
        benefits2: 'Medical Insurance (Hospitalization & Outpatient)',
        benefits3: '14 days Paid Leave',
        benefits4: '17 days Public Holiday',
    },
        {
        id: '17',
        post_date: '15-08-2025',
        job_title: 'Field Researcher',
        department: 'Discovery & Education',
        job_type: 'Full-time / Long-term',
        link: '#',
        responsibilities1: 'Prepare invoices / vouchers on a daily basis and support the account payables and receivables functions of the Finance Department',
        responsibilities2: 'Perform annual spot check of Fixed Assets',
        responsibilities3: 'Perform monthly surprise stock check and annual stock take',
        responsibilities4: 'Perform ad hoc assignments as and when required',
        requirements1: "Bachelor's Degree in Accounting or at least one year of relevant working experience",
        requirements2: 'Able to work under pressure, and commit to reporting deadlines',
        requirements3: 'Detailed-oriented and with strong sense of responsibilities',
        requirements4: 'Well-organized, and a team player with the ability to work with parties across different departments',
        benefits1: '13-month payment / Gratuity',
        benefits2: 'Medical Insurance (Hospitalization & Outpatient)',
        benefits3: '14 days Paid Leave',
        benefits4: '17 days Public Holiday',
    },
        {
        id: '18',
        post_date: '15-08-2025',
        job_title: 'LSO Operator ',
        department: 'Life Support Operations',
        job_type: 'Full-time / Long-term',
        link: '#',
        responsibilities1: 'Prepare invoices / vouchers on a daily basis and support the account payables and receivables functions of the Finance Department',
        responsibilities2: 'Perform annual spot check of Fixed Assets',
        responsibilities3: 'Perform monthly surprise stock check and annual stock take',
        responsibilities4: 'Perform ad hoc assignments as and when required',
        requirements1: "Bachelor's Degree in Accounting or at least one year of relevant working experience",
        requirements2: 'Able to work under pressure, and commit to reporting deadlines',
        requirements3: 'Detailed-oriented and with strong sense of responsibilities',
        requirements4: 'Well-organized, and a team player with the ability to work with parties across different departments',
        benefits1: '13-month payment / Gratuity',
        benefits2: 'Medical Insurance (Hospitalization & Outpatient)',
        benefits3: '14 days Paid Leave',
        benefits4: '17 days Public Holiday',
    },
        {
        id: '19',
        post_date: '15-08-2025',
        job_title: 'Assistant Clinical Laboratory Manager',
        department: 'Clinical Laboratory',
        job_type: 'Full-time / Long-term',
        link: '#',
        responsibilities1: 'Prepare invoices / vouchers on a daily basis and support the account payables and receivables functions of the Finance Department',
        responsibilities2: 'Perform annual spot check of Fixed Assets',
        responsibilities3: 'Perform monthly surprise stock check and annual stock take',
        responsibilities4: 'Perform ad hoc assignments as and when required',
        requirements1: "Bachelor's Degree in Accounting or at least one year of relevant working experience",
        requirements2: 'Able to work under pressure, and commit to reporting deadlines',
        requirements3: 'Detailed-oriented and with strong sense of responsibilities',
        requirements4: 'Well-organized, and a team player with the ability to work with parties across different departments',
        benefits1: '13-month payment / Gratuity',
        benefits2: 'Medical Insurance (Hospitalization & Outpatient)',
        benefits3: '14 days Paid Leave',
        benefits4: '17 days Public Holiday',
    },
        {
        id: '20',
        post_date: '15-08-2025',
        job_title: 'Senior Accounting Assistant',
        department: 'Finance',
        job_type: 'Full-time / Long-termASK',
        link: '#',
        responsibilities1: 'Prepare invoices / vouchers on a daily basis and support the account payables and receivables functions of the Finance Department',
        responsibilities2: 'Perform annual spot check of Fixed Assets',
        responsibilities3: 'Perform monthly surprise stock check and annual stock take',
        responsibilities4: 'Perform ad hoc assignments as and when required',
        requirements1: "Bachelor's Degree in Accounting or at least one year of relevant working experience",
        requirements2: 'Able to work under pressure, and commit to reporting deadlines',
        requirements3: 'Detailed-oriented and with strong sense of responsibilities',
        requirements4: 'Well-organized, and a team player with the ability to work with parties across different departments',
        benefits1: '13-month payment / Gratuity',
        benefits2: 'Medical Insurance (Hospitalization & Outpatient)',
        benefits3: '14 days Paid Leave',
        benefits4: '17 days Public Holiday',
    },
]

